# Generated by Django 4.0.1 on 2022-01-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
